<?xml version="1.0"?>
<!DOCTYPE Report
[
<!ELEMENT Report (General ,(Doc|BPT)) >
<!ATTLIST Report ver CDATA #REQUIRED tmZone CDATA #REQUIRED>

<!ELEMENT General ( DocLocation ) >
<!ATTLIST General productName CDATA #REQUIRED productVer CDATA #REQUIRED os CDATA #REQUIRED host CDATA #REQUIRED qcserver CDATA #IMPLIED qcproject CDATA #IMPLIED SolManSolutionId CDATA #IMPLIED SolManProjectId CDATA #IMPLIED SolManTestPlanId CDATA #IMPLIED SolManTestPackageId CDATA #IMPLIED SolManUserInfoData CDATA #IMPLIED  >

<!ELEMENT BPT (DName,Res,DVer?,TSet?,TInst?,NodeArgs,AdditionalInfo*,Doc*) >
<!ATTLIST BPT rID ID #REQUIRED >

<!ELEMENT Doc (DName,ConfName?,Res,DVer?,TSet?,TInst?,RunType?,DT?,AdditionalInfo*,Step*,DIter*,Step*,Action*,Doc*,Summary?,TestMaintenanceSummary*,NodeArgs?) >
<!ATTLIST Doc rID ID #REQUIRED type (Test|BC|BPTWrapperTest|Flow|Group|Action) "Test" productName CDATA #REQUIRED BCIter CDATA #IMPLIED >

<!ELEMENT RunType ( #PCDATA )>
<!ATTLIST RunType fmStep (False|True) "False" batch (False|True) "False" upDesc (False|True) "False" upChk (False|True) "False" upAS (False|True) "False">

<!ELEMENT DName ( #PCDATA ) >

<!ELEMENT ConfName ( #PCDATA ) >

<!ELEMENT Res ( #PCDATA ) >

<!ELEMENT AdditionalInfo (AdditionalDataName,AdditionalDataValue ) >

<!ELEMENT AdditionalDataName ( #PCDATA ) >

<!ELEMENT AdditionalDataValue ( #PCDATA ) >

<!ELEMENT DVer ( #PCDATA ) >

<!ELEMENT TSet ( #PCDATA ) >

<!ELEMENT TInst ( #PCDATA ) >

<!ELEMENT DIter (Step*,Action+,Summary?,NodeArgs)>
<!ATTLIST DIter rID ID #REQUIRED iterID CDATA #REQUIRED>

<!ELEMENT DocLocation ( #PCDATA )>

<!ELEMENT Action (AName,AIter*,(Step|HtmlStep|Action)*, Summary,ActionMaintenanceSummary*, NodeArgs ) >
<!ATTLIST Action rID ID #REQUIRED>

<!ELEMENT AIter ((Step|HtmlStep|Action)*,DataMapping?, Summary?,NodeArgs) >
<!ATTLIST AIter rID ID #REQUIRED iterID CDATA #REQUIRED isCountable (False|True) "False" >

<!ELEMENT AName ( #PCDATA ) >

<!ELEMENT TestMaintenanceSummary (ActionMaintenanceSummary*) >
<!ATTLIST TestMaintenanceSummary ObjectsAdded CDATA #REQUIRED ObjectsUpdated CDATA #REQUIRED StepsUpdated CDATA #REQUIRED StepsComments CDATA #REQUIRED><!ELEMENT ActionMaintenanceSummary (ObjectChange* ) >
<!ATTLIST ActionMaintenanceSummary Action CDATA #REQUIRED Objects CDATA #REQUIRED Updated CDATA #REQUIRED LinesTotal CDATA #REQUIRED Added CDATA #REQUIRED LinesUpdated CDATA #REQUIRED>

<!ELEMENT ObjectChange  (Hierarchy, PropertyChangeList* ) >
<!ATTLIST ObjectChange Operation CDATA #IMPLIED OriginalRepository CDATA #IMPLIED>

<!ELEMENT PropertyChangeList (PropertyDef*) >

<!ELEMENT PropertyDef (OriginalValue, NewValue) >
<!ATTLIST PropertyDef PropName CDATA #REQUIRED OriginRegularExpression (True|False) "False" NewRegularExpression (True|False) "False" AddedProperty (True|False) "False" >

<!ELEMENT OriginalValue ( #PCDATA )>

<!ELEMENT NewValue ( #PCDATA )>

<!ELEMENT Hierarchy  (ObjectName, Hierarchy*) >
<!ATTLIST Hierarchy MicClass CDATA #REQUIRED>

<!ELEMENT ObjectName  ( #PCDATA ) >

<!ELEMENT Step (Obj,Details,Time,TimeTick* ,(Step|HtmlStep|Doc)*, DataMapping?, NodeArgs) >
<!ATTLIST Step rID ID #REQUIRED retval CDATA #IMPLIED>

<!ELEMENT HtmlStep (HTML,TimeTick*,(Step|HtmlStep|Doc)*,NodeArgs) >
<!ATTLIST HtmlStep rID ID #REQUIRED >

<!ELEMENT Obj ( #PCDATA ) >
<!ATTLIST Obj plainTxt (False|True) "True">

<!ELEMENT Details ( #PCDATA ) >
<!ATTLIST Details plainTxt (False|True) "True">

<!ELEMENT Time ( #PCDATA ) >

<!ELEMENT HTML ( #PCDATA ) >

<!ELEMENT Disp ( #PCDATA ) >

<!ELEMENT TimeTick ( #PCDATA ) >

<!ELEMENT DataMapping ( DataMappedItem* )>
<!ELEMENT DataMappedItem EMPTY >
<!ATTLIST DataMappedItem dsName CDATA #REQUIRED >
<!ATTLIST DataMappedItem rowId CDATA #REQUIRED >

<!ELEMENT NodeArgs (Disp,TopPane?,BtmPane?,ExtendedInfo? )>
<!ATTLIST NodeArgs eType CDATA #REQUIRED icon CDATA #REQUIRED nRep CDATA #REQUIRED UserNote CDATA #IMPLIED filter (False|True) "True">
<!ATTLIST NodeArgs status (Passed|Failed|Done|Warning|Information) "Done">
<!ATTLIST NodeArgs iconSel CDATA #IMPLIED nType CDATA #IMPLIED MovieMarker CDATA "">
<!ATTLIST NodeArgs Source CDATA #IMPLIED SourceLine CDATA #IMPLIED StepFlowItemKey CDATA #IMPLIED >

<!ELEMENT TopPane (Path)>

<!ELEMENT BtmPane ( (Path|WR)?,ASHilite?)>
<!ATTLIST BtmPane vType CDATA "HTML">

<!ELEMENT Path ( #PCDATA ) >

<!ELEMENT ASHilite ( #PCDATA ) >

<!ELEMENT WR ( #PCDATA ) >

<!ELEMENT ExtendedInfo ( StepData ) >

<!ATTLIST ExtendedInfo StepType CDATA #REQUIRED>
<!ELEMENT DT (NodeArgs) >
<!ATTLIST DT rID ID #REQUIRED>

<!ELEMENT Summary (Param*)>
<!ATTLIST Summary sTime CDATA #IMPLIED eTime CDATA #IMPLIED passed CDATA #IMPLIED failed CDATA #IMPLIED warnings CDATA #IMPLIED retval CDATA #IMPLIED stopped (False|True) "False" >

<!ELEMENT Param (ParamName,ParamVal)+ >
<!ATTLIST Param paramInOut (In|Out) "In">

<!ELEMENT ParamName ( #PCDATA ) >

<!ELEMENT ParamVal ( #PCDATA ) >

]
>
<Report ver="2.0" tmZone="India Standard Time">
<General productName="HPE Unified Functional Testing" productVer="14.03" os="" host="WINDOWS-UNR7VLH"><DocLocation><![CDATA[C:\Users\Administrator\Documents\Unified Functional Testing\Day 3 lab 2 data driven testing]]></DocLocation></General>
<Doc rID="T1"   productName= "HPE Unified Functional Testing"  >
<DName><![CDATA[Day 3 lab 2 data driven testing]]></DName>
<Res><![CDATA[Res6]]></Res>
<DT rID="T2">
<NodeArgs eType="Table" icon="2" nRep="4" filter="False" >
<Disp><![CDATA[Run-Time Data Table]]></Disp>
<BtmPane vType="Table" >
<Path><![CDATA[Default.xls]]></Path>
</BtmPane>
</NodeArgs>
</DT>
<DIter rID="T3" iterID="1" >
<Action rID="T4">
<AName><![CDATA[Action1]]></AName>
<Step rID="T5">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:20]]></Time>
<TimeTick>1678691240</TimeTick>
<Step rID="T6">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:20]]></Time>
<TimeTick>1678691240</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="11" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="10" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T7">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:25]]></Time>
<TimeTick>1678691245</TimeTick>
<Step rID="T8">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:25]]></Time>
<TimeTick>1678691245</TimeTick>
<Step rID="T9">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:25]]></Time>
<TimeTick>1678691245</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="16" Source="Action1" SourceLine="1" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T10">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["vk@gmail.com"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:25]]></Time>
<TimeTick>1678691245</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="19" Source="Action1" SourceLine="2" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T11">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["vk"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:25]]></Time>
<TimeTick>1678691245</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="22" Source="Action1" SourceLine="3" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T12">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:25]]></Time>
<TimeTick>1678691245</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="25" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="15" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="14" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:37:20" eTime="13-03-2023 - 12:37:25" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="7" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="6" status="Passed" >
<Disp><![CDATA[Day 3 lab 2 data driven testing Iteration 1 (Row 1)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T13" iterID="2" >
<Action rID="T14">
<AName><![CDATA[Action1]]></AName>
<Step rID="T15">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:26]]></Time>
<TimeTick>1678691246</TimeTick>
<Step rID="T16">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:26]]></Time>
<TimeTick>1678691246</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="33" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="32" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T17">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:28]]></Time>
<TimeTick>1678691248</TimeTick>
<Step rID="T18">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:28]]></Time>
<TimeTick>1678691248</TimeTick>
<Step rID="T19">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:28]]></Time>
<TimeTick>1678691248</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="38" Source="Action1" SourceLine="1" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T20">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["cd@gmail.com"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:29]]></Time>
<TimeTick>1678691249</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="41" Source="Action1" SourceLine="2" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T21">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["cd"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:29]]></Time>
<TimeTick>1678691249</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="44" Source="Action1" SourceLine="3" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T22">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:30]]></Time>
<TimeTick>1678691250</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="47" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="37" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="36" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:37:26" eTime="13-03-2023 - 12:37:30" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="29" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="28" status="Passed" >
<Disp><![CDATA[Day 3 lab 2 data driven testing Iteration 2 (Row 2)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T23" iterID="3" >
<Action rID="T24">
<AName><![CDATA[Action1]]></AName>
<Step rID="T25">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:30]]></Time>
<TimeTick>1678691250</TimeTick>
<Step rID="T26">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:30]]></Time>
<TimeTick>1678691250</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="55" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="54" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T27">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:33]]></Time>
<TimeTick>1678691253</TimeTick>
<Step rID="T28">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:33]]></Time>
<TimeTick>1678691253</TimeTick>
<Step rID="T29">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:33]]></Time>
<TimeTick>1678691253</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="60" Source="Action1" SourceLine="1" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T30">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ef@gmail.com"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:34]]></Time>
<TimeTick>1678691254</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="63" Source="Action1" SourceLine="2" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T31">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["ef"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:34]]></Time>
<TimeTick>1678691254</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="66" Source="Action1" SourceLine="3" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T32">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:34]]></Time>
<TimeTick>1678691254</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="69" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="59" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="58" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:37:30" eTime="13-03-2023 - 12:37:34" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="51" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="50" status="Passed" >
<Disp><![CDATA[Day 3 lab 2 data driven testing Iteration 3 (Row 3)]]></Disp>
</NodeArgs>
</DIter>
<DIter rID="T33" iterID="4" >
<Action rID="T34">
<AName><![CDATA[Action1]]></AName>
<Step rID="T35">
<Obj plainTxt="False" ><![CDATA[SystemUtil]]></Obj>
<Details plainTxt="False" ><![CDATA[SystemUtil]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:35]]></Time>
<TimeTick>1678691255</TimeTick>
<Step rID="T36">
<Obj plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Obj>
<Details plainTxt="False" ><![CDATA[Run "https://demo.opencart.com/",1]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:35]]></Time>
<TimeTick>1678691255</TimeTick>
<NodeArgs eType="Replay" icon="5" nRep="77" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[Run "https://demo.opencart.com/",1]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Replay" icon="5" nRep="76" status="Passed" Source="Action1" SourceLine="0" >
<Disp><![CDATA[SystemUtil]]></Disp>
</NodeArgs>
</Step>
<Step rID="T37">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[<table><tr><td><span style="text-align : left; font-size : 12px; ">Local Browser</span></td></tr></table>]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:37]]></Time>
<TimeTick>1678691257</TimeTick>
<Step rID="T38">
<Obj plainTxt="False" ><![CDATA[Account Login]]></Obj>
<Details plainTxt="False" ><![CDATA[Page]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:37]]></Time>
<TimeTick>1678691257</TimeTick>
<Step rID="T39">
<Obj plainTxt="False" ><![CDATA[My Account.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:37]]></Time>
<TimeTick>1678691257</TimeTick>
<NodeArgs eType="Replay" icon="8" nRep="82" Source="Action1" SourceLine="1" >
<Disp><![CDATA[My Account.Click]]></Disp>
</NodeArgs>
</Step>
<Step rID="T40">
<Obj plainTxt="False" ><![CDATA[email.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["gh@gmail.com"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:38]]></Time>
<TimeTick>1678691258</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="85" Source="Action1" SourceLine="2" >
<Disp><![CDATA[email.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T41">
<Obj plainTxt="False" ><![CDATA[password.Set]]></Obj>
<Details plainTxt="False" ><![CDATA["gh"]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:38]]></Time>
<TimeTick>1678691258</TimeTick>
<NodeArgs eType="Replay" icon="9" nRep="88" Source="Action1" SourceLine="3" >
<Disp><![CDATA[password.Set]]></Disp>
</NodeArgs>
</Step>
<Step rID="T42">
<Obj plainTxt="False" ><![CDATA[Login.Click]]></Obj>
<Details plainTxt="False" ><![CDATA[]]></Details>
<Time><![CDATA[13-03-2023 - 12:37:38]]></Time>
<TimeTick>1678691258</TimeTick>
<NodeArgs eType="Replay" icon="10" nRep="91" Source="Action1" SourceLine="4" >
<Disp><![CDATA[Login.Click]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="7" nRep="81" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<NodeArgs eType="Context" icon="6" nRep="80" Source="Action1" SourceLine="1" >
<Disp><![CDATA[Account Login]]></Disp>
</NodeArgs>
</Step>
<Summary sTime="13-03-2023 - 12:37:34" eTime="13-03-2023 - 12:37:38" passed="1" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartAction" icon="4" nRep="73" status="Passed" >
<Disp><![CDATA[Action1 Summary]]></Disp>
</NodeArgs>
</Action>
<NodeArgs eType="StartIteration" icon="3" nRep="72" status="Passed" >
<Disp><![CDATA[Day 3 lab 2 data driven testing Iteration 4 (Row 4)]]></Disp>
</NodeArgs>
</DIter>
<Summary sTime="13-03-2023 - 12:37:18" eTime="13-03-2023 - 12:37:38" passed="4" failed="0" warnings="0" ></Summary>
<NodeArgs eType="StartTest" icon="1" nRep="3" status="Passed" >
<Disp><![CDATA[Test Day 3 lab 2 data driven testing Summary]]></Disp>
</NodeArgs>
</Doc>
</Report>